services:
  - type: web
    name: piazza-web
    env: ruby
    plan: free
    region: frankfurt
    numInstances: 1
    buildCommand: bin/build
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: piazza-db
          property: connectionString
      - key: RAILS_ENVIRONMENT
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: true

databases:
  - name: piazza-db
    plan: free
    region: frankfurt
    postgresMajorVersion: 14
